# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-21 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserConsumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('date_time', models.DateTimeField()),
                ('comsump_data', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_area', models.CharField(max_length=255)),
                ('user_tariff', models.CharField(max_length=255)),
            ],
        ),
    ]
